package app.cash.sqldelight.paging3

import androidx.paging.PagingSource
import app.cash.sqldelight.Query
import app.cash.sqldelight.Transacter
import app.cash.sqldelight.db.QueryResult
import app.cash.sqldelight.db.SqlCursor
import kotlinx.coroutines.Dispatchers
import kotlin.coroutines.CoroutineContext
import kotlin.jvm.JvmName
import kotlin.properties.Delegates

internal abstract class QueryPagingSource<Key : Any, RowType : Any> :
    PagingSource<Key, RowType>(),
    Query.Listener {

    protected var currentQuery: Query<RowType>? by Delegates.observable(null) { _, old, new ->
        old?.removeListener(this)
        new?.addListener(this)
    }

    init {
        registerInvalidatedCallback {
            currentQuery?.removeListener(this)
            currentQuery = null
        }
    }

    final override fun queryResultsChanged() = invalidate()
}

/**
 * Create a [PagingSource] that pages through results according to queries generated by
 * [queryProvider]. Queries returned by [queryProvider] should expect to do SQL offset/limit
 * based paging. For that reason, [countQuery] is required to calculate pages and page offsets.
 *
 * An example query returned by [queryProvider] could look like:
 *
 * ```sql
 * SELECT value FROM numbers
 * LIMIT 10
 * OFFSET 100;
 * ```
 *
 * Queries will be executed on [context].
 */
@Suppress("FunctionName")
@JvmName("QueryPagingSourceInt")
fun <RowType : Any> QueryPagingSource(
    countQuery: Query<Int>,
    transacter: Transacter,
    context: CoroutineContext = Dispatchers.Default,
    queryProvider: (limit: Int, offset: Int) -> Query<RowType>,
): PagingSource<Int, RowType> = OffsetQueryPagingSource(
    queryProvider,
    countQuery,
    transacter,
    context,
)

/**
 * Variant of [QueryPagingSource] that accepts a [Long] instead of an [Int] for [countQuery]
 * and [queryProvider].
 *
 * If the result of [countQuery] exceeds [Int.MAX_VALUE], then the count will be truncated
 * to the least significant 32 bits of this [Long] value.
 *
 * @see toInt
 */
@Suppress("FunctionName")
fun <RowType : Any> QueryPagingSource(
    countQuery: Query<Long>,
    transacter: Transacter,
    context: CoroutineContext = Dispatchers.Default,
    queryProvider: (limit: Long, offset: Long) -> Query<RowType>,
): PagingSource<Int, RowType> = OffsetQueryPagingSource(
    { limit, offset -> queryProvider(limit.toLong(), offset.toLong()) },
    countQuery.toInt(),
    transacter,
    context,
)

private fun Query<Long>.toInt(): Query<Int> =
    object : Query<Int>({ cursor -> mapper(cursor).toInt() }) {
        override fun <R> execute(mapper: (SqlCursor) -> QueryResult<R>) = this@toInt.execute(mapper)
        override fun addListener(listener: Listener) = this@toInt.addListener(listener)
        override fun removeListener(listener: Listener) = this@toInt.removeListener(listener)
    }
