name: Check CI

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
  push:
    branches:
      - main

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true


jobs:
  spotless:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Check spotless
        run: ./gradlew spotlessCheck --stacktrace

      - name: Check swiftlint
        run: fastlane ios lint
        working-directory: iosApp

  build-android:
    needs: spotless
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build Android App
        run: |
          ./gradlew \
            :androidApp:bundle \
            :androidApp:build

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-build-outputs
          path: androidApp/build/outputs

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-reports
          path: |
            **/build/reports/*

  build-ios:
    needs: spotless
    runs-on: macos-13
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@ff740bc00a01b3a50fffc55a1071b1060eeae9dc # v1.180.0
        with:
          bundler-cache: true

      - name: read .xcode-version
        shell: bash
        run: |
          echo "XCODE_VERSION=$(grep -oE "\d+(\.\d+)+" .xcode-version | awk -F. '{print $1 ".0"}' | uniq)" >> $GITHUB_ENV

      - name: execute xcode-select
        shell: bash
        run: |
          echo "select $XCODE_VERSION"
          sudo xcode-select --switch "/Applications/Xcode_$XCODE_VERSION.app"

      - name: Build iOS application
        run: bundle exec fastlane build_project
        working-directory: iosApp

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ios-logs
          path: |
            **/fastlane-buildlog
